---
output:
  html_document:
    toc: true
    toc_float: true
---

# Labs
#### 16% of your overall grade
#### 40 points total; 10 points each

You are encouraged to work in partners or teams of up to 4 people on labs.
However, should you choose to work in teams, labs **must** be submitted as a
shared GitHub repository. I will evaluate the commits made by team members
before assigning final points.

|**Lab** | **Topic**                          | **Assigned** | **Due** | 
|:------:| :----------------------------------| :------------| :-------| 
| 1      | Iterations with Base R             | 4/10/19      | 4/17/19 | 
| 2      | Iterations with {purrr}            | 4/17/19      | 4/24/19 |
| 3      | Writing Functions 1                | 5/8/19       | 5/15/19 | 
| 4      | Writing Functions 2                | 5/15/19      | 5/22/19 | 

# DataCamp
#### 4% of your overall grade
#### 10 points total (5 points available for extra credit)

One complete course is required. You may choose among any of the following, and
the due dates depend upon which course you select (to align with the topic
coverage). You may complete one course in each section for up to 5 points 
extra credit.

#### First 5 week DataCamp courses 
##### Due by 11:59 PM, 5/6/19 
* [Intermediate R](https://www.datacamp.com/courses/intermediate-r)
* [Foundations of functional programming with purrr](https://www.datacamp.com/courses/foundations-of-functional-programming-with-purrr)
* [Intermediate functional programming with purrr](https://www.datacamp.com/courses/intermediate-functional-programming-with-purrr)
* [Machine learning in the tidyverse](https://www.datacamp.com/courses/machine-learning-in-the-tidyverse)

#### Second 5 week DataCamp courses
##### Due by 11:59 PM, 6/12/19
* [Writing functions in R](https://www.datacamp.com/courses/writing-functions-in-r)
* [Building web applications in R with Shiny](https://www.datacamp.com/courses/building-web-applications-in-r-with-shiny)
* [Building web applications in R with Shiny: Case studies](https://www.datacamp.com/courses/building-web-applications-in-r-with-shiny-case-studies)
* [Developing R packages](https://www.datacamp.com/courses/developing-r-packages)
* [Writing efficient R code](https://www.datacamp.com/courses/writing-efficient-r-code)

# Midterm
#### 20% of your overall grade
#### 50 points total

**Assigned**: 4/22/19

**Due**: 5/6/19

More details will be available later in the term, but a midterm will be 
assigned, which will likely ask you to rewrite code to accomplish a similar 
task using more efficient and/or readable approaches.

# Final Project
#### 60% of your overall grade
#### 150 points total

|**Component** | **Points**| **Due** | 
|:-------------|:----------|:--------| 
| Groups Finalized | 0 | 4/10/19|
| [Outline](https://uo-datasci-specialization.github.io/c3-fun_program_r/site-syllabus.html#outline_(10_points;_5%))  | 10 | 5/1/19 | 
| [Draft](https://uo-datasci-specialization.github.io/c3-fun_program_r/site-syllabus.html#draft_data_preparation_script_(20_points)) |  20 | 5/27/19 | 
| [Peer review](https://uo-datasci-specialization.github.io/c3-fun_program_r/site-syllabus.html#peer_review_of_data_preparation_script_(20_points)) | 20 | 6/3/19 | 
| [Product](https://uo-datasci-specialization.github.io/c3-fun_program_r/site-syllabus.html#final_product_grading_(100_points)) |  100 | 6/12/19 (11:59 pm) | 



